# [Modified] Introduce math for the subsequent calculation of Math.exp () conversion confusion
# [Modified] Introduced the functional module of PyTorch for calculating F.log_softmax
import math
import torch.nn.functional as F


class BLIP2Captioner(Captioner):
    def __init__(self, batch_size=20, device='cuda:0'):
        self.batch_size = batch_size
        self.device = device
        self.processor = None
        self.model = None
        super().__init__(device)
        self._init_models()

    def _init_models(self):
        """Initialize the processor and model"""
        try:
            # Change the quantization configuration to avoid float16/half precision
            quantization_config = BitsAndBytesConfig(
                load_in_8bit=True,
            )

            processor = Blip2Processor.from_pretrained("Salesforce/blip2-opt-2.7b", use_fast=True)

            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                model = Blip2ForConditionalGeneration.from_pretrained(
                    "Salesforce/blip2-opt-2.7b",
                    quantization_config=quantization_config,
                    device_map='auto',
                    torch_dtype=torch.float32,  # Explicitly request float32
                )

            processor.num_query_tokens = model.config.num_query_tokens
            image_token = AddedToken("<image>", normalized=False, special=True)
            processor.tokenizer.add_tokens([image_token], special_tokens=True)

            model.resize_token_embeddings(len(processor.tokenizer), pad_to_multiple_of=64) # pad for efficient computation
            model.config.image_token_index = len(processor.tokenizer) - 1

            self.processor = processor
            self.model = model
        except Exception as e:
            print(f"Error initializing models: {e}")
            raise

    # [Modified] A brand-new method for extracting and calculating various indicators during the generation process
    def compute_stats(self, outputs):
        sequences = outputs.sequences
        scores = outputs.scores
        batch_size = sequences.shape[0]
        gen_len = len(scores)
        
        all_stats = []
        # [Modified] Calculate the starting index of the generation part. Code before has a large perplexity here.
        # [Modified] This is because outputs.sequences contain the tokens generated by the input prompt. Now only evaluate the probability of the "generated" part of the tokens.
        start_idx = sequences.shape[1] - gen_len

        for batch_idx in range(batch_size):
            # the next line is changed to fix the large perplexity problem(originally made by me as well) 
            # generated_token_ids = sequences[batch_idx, prompt_len:prompt_len + gen_len]
            generated_token_ids = sequences[batch_idx, start_idx:]
            token_logprobs = []

            # [Modified] Traverse each step generated and extract the corresponding score (logits)
            for step_idx, step_scores in enumerate(scores):
                # [Modified] Convert the original logits to log probabilities
                log_probs = F.log_softmax(step_scores[batch_idx], dim = -1)
                token_id = generated_token_ids[step_idx].item()
                # [Modified] Retrieve the log probability corresponding to the actually generated token
                token_logprob = log_probs[token_id].item()
                token_logprobs.append(token_logprob)
            if len(token_logprobs) > 0:
                # [Modified] Calculate the average logarithmic probability
                avg_logprob = sum(token_logprobs) / len(token_logprobs)
                # [Modified] Calculate Perplexity: The (-mean logarithmic probability) power of e. The lower the value, the higher the confidence of the model in generating the sentence, and the better the quality is usually.
                perplexity = math.exp(-avg_logprob)
            else:
                avg_logprob = None
                perplexity = None

            all_stats.append({
                "token_logprobs": token_logprobs,
                "avg_logprob": avg_logprob,
                "perplexity": perplexity
            })

        return all_stats

    # [Modified] The function signature has added the return_stats=False parameter, allowing external control over whether statistical information needs to be returned
    def caption(self, imgs, user_prompt=None, return_stats=False):
        """Caption the given images"""
        # Initialize models if they haven't been initialized
        if self.processor is None or self.model is None:
            self._init_models()

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            with torch.no_grad():
                num_batches = int(np.ceil(len(imgs) / self.batch_size))
                captions = []
                all_stats = []
                print('Captioning objects with BLIP2 with batch size: ', self.batch_size)

                for batch_idx in tqdm(range(num_batches)):
                    batch_imgs = imgs[batch_idx * self.batch_size : (batch_idx + 1) * self.batch_size]
                    inputs = self.processor(images=batch_imgs, return_tensors="pt").to(self.model.device, torch.float16)
                    prompt_len = inputs["input_ids"].shape[1] if "input_ids" in inputs else 0
                    
                    # [Modified] Originally it was generated_ids = self.model.generate(**inputs)
                    # [Modified] Now, additional parameters have been added to force the model to return the dictionary format and output the scores (predicted probability) for each step, while limiting the maximum generation length to 50
                    outputs = self.model.generate(
                        **inputs,
                        return_dict_in_generate=True,
                        output_scores=True,
                        max_new_tokens=50
                    )

                    #       generated_ids = self.model.generate(**inputs)
                    #        batch_captions = self.processor.batch_decode(generated_ids, skip_special_tokens=True)
                    # [Modified] Since the previous step returned a dict instead of a simple tensor, it is necessary to explicitly specify outputs.sequences during decoding
                    batch_captions = self.processor.batch_decode(
                        outputs.sequences,
                        skip_special_tokens = True
                    )
                    batch_captions = [caption.strip() for caption in batch_captions]
                    captions.extend(batch_captions)

                    # [Modified] If the call requires the return of statistical information, then call compute_stats to extract the metric
                    if return_stats:
                        # next is my implementation before as well  
                        #  batch_stats = self.compute_stats(outputs, prompt_len)
                        batch_stats = self.compute_stats(outputs)
                        all_stats.extend(batch_stats)
                        
                # [Modified] Determine whether to return a single value or a tuple based on the status of return_stats
                if return_stats:
                    return captions, all_stats

                return captions

                #     captions.extend(batch_captions)
                #   captions = [caption.strip() for caption in captions]
                #  return captions

    def stop(self):
        """Stop the captioner"""
        if self.model is not None:
            self.model = None
        if self.processor is not None:
            self.processor = None
        torch.cuda.empty_cache()